spring.application.name=general-templatespring:
  application:
    name: yu-code-mother
  # session 配置
  session:
    store-type: redis
    # session 1 天过期
    timeout: 86400

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600

  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 1 天过期
    session:
      cookie:
        max-age: 86400
